/******************************************************************************/
/***          Generated by IBExpert 2011.04.06 05.06.2020 10:33:22          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

CREATE DATABASE 'C:\Db\Support\SUPPORT.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;



/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN T_BOOL AS
INTEGER;

CREATE DOMAIN T_COUNT AS
INTEGER;

CREATE DOMAIN T_DATE AS
DATE;

CREATE DOMAIN T_EQUIPNAME AS
VARCHAR(50);

CREATE DOMAIN T_EQUIPTYPENAME AS
VARCHAR(30);

CREATE DOMAIN T_FIO AS
VARCHAR(50);

CREATE DOMAIN T_FM AS
VARCHAR(30);

CREATE DOMAIN T_ID AS
INTEGER;

CREATE DOMAIN T_IM AS
VARCHAR(30);

CREATE DOMAIN T_MARK AS
INTEGER;

CREATE DOMAIN T_NOTE AS
VARCHAR(100);

CREATE DOMAIN T_OT AS
VARCHAR(30);

CREATE DOMAIN T_REGN AS
VARCHAR(10);

CREATE DOMAIN T_ROOMNO AS
VARCHAR(10);

CREATE DOMAIN T_SERVICENAME AS
VARCHAR(50);

CREATE DOMAIN T_SOFTNAME AS
VARCHAR(50);

CREATE DOMAIN T_TASK AS
VARCHAR(150);



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CHANGEPLACE_ID;
SET GENERATOR GEN_CHANGEPLACE_ID TO 3;

CREATE GENERATOR GEN_EQUIPPART_ID;
SET GENERATOR GEN_EQUIPPART_ID TO 3;

CREATE GENERATOR GEN_EQUIPSERVICE_ID;
SET GENERATOR GEN_EQUIPSERVICE_ID TO 1;

CREATE GENERATOR GEN_EQUIPSOFT_ID;
SET GENERATOR GEN_EQUIPSOFT_ID TO 48;

CREATE GENERATOR GEN_EQUIPTYPE_ID;
SET GENERATOR GEN_EQUIPTYPE_ID TO 7;

CREATE GENERATOR GEN_EQUIP_ID;
SET GENERATOR GEN_EQUIP_ID TO 60;

CREATE GENERATOR GEN_ITMAN_ID;
SET GENERATOR GEN_ITMAN_ID TO 1;

CREATE GENERATOR GEN_ORDERS_ID;
SET GENERATOR GEN_ORDERS_ID TO 2;

CREATE GENERATOR GEN_ROOM_ID;
SET GENERATOR GEN_ROOM_ID TO 26;

CREATE GENERATOR GEN_SERVICE_ID;
SET GENERATOR GEN_SERVICE_ID TO 9;

CREATE GENERATOR GEN_SOFT_ID;
SET GENERATOR GEN_SOFT_ID TO 28;

CREATE GENERATOR GEN_SOTRUD_ID;
SET GENERATOR GEN_SOTRUD_ID TO 32;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE CHANGEPLACE_DEL (
    ID INTEGER /* TYPE OF COLUMN CHANGEPLACE.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE CHANGEPLACE_INS (
    EQUIPID INTEGER /* TYPE OF COLUMN CHANGEPLACE.EQUIPID */,
    ROOMID INTEGER /* TYPE OF COLUMN CHANGEPLACE.ROOMID */,
    DAYOF DATE /* TYPE OF COLUMN CHANGEPLACE.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN CHANGEPLACE.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN CHANGEPLACE.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE CHANGEPLACE_UPD (
    ID INTEGER /* TYPE OF COLUMN CHANGEPLACE.ID */,
    EQUIPID INTEGER /* TYPE OF COLUMN CHANGEPLACE.EQUIPID */,
    ROOMID INTEGER /* TYPE OF COLUMN CHANGEPLACE.ROOMID */,
    DAYOF DATE /* TYPE OF COLUMN CHANGEPLACE.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN CHANGEPLACE.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIP_DEL (
    ID INTEGER /* TYPE OF COLUMN EQUIP.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIP_INS (
    EQUIPTYPEID INTEGER /* TYPE OF COLUMN EQUIP.EQUIPTYPEID */,
    REGN VARCHAR(10) /* TYPE OF COLUMN EQUIP.REGN */,
    NAME VARCHAR(50) /* TYPE OF COLUMN EQUIP.NAME */,
    DAYOF DATE /* TYPE OF COLUMN EQUIP.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIP.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN EQUIP.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE EQUIP_UPD (
    ID INTEGER /* TYPE OF COLUMN EQUIP.ID */,
    EQUIPTYPEID INTEGER /* TYPE OF COLUMN EQUIP.EQUIPTYPEID */,
    REGN VARCHAR(10) /* TYPE OF COLUMN EQUIP.REGN */,
    NAME VARCHAR(50) /* TYPE OF COLUMN EQUIP.NAME */,
    DAYOF DATE /* TYPE OF COLUMN EQUIP.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIP.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPPART_DEL (
    ID INTEGER /* TYPE OF COLUMN EQUIPPART.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPPART_INS (
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPPART.EQUIPID */,
    EQUIPPARTID INTEGER /* TYPE OF COLUMN EQUIPPART.EQUIPPARTID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPPART.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPPART.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN EQUIPPART.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE EQUIPPART_UPD (
    ID INTEGER /* TYPE OF COLUMN EQUIPPART.ID */,
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPPART.EQUIPID */,
    EQUIPPARTID INTEGER /* TYPE OF COLUMN EQUIPPART.EQUIPPARTID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPPART.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPPART.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPSERVICE_DEL (
    ID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPSERVICE_INS (
    ORDERID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.ORDERID */,
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.EQUIPID */,
    SERVICEID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.SERVICEID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPSERVICE.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPSERVICE.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE EQUIPSERVICE_UPD (
    ID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.ID */,
    ORDERID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.ORDERID */,
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.EQUIPID */,
    SERVICEID INTEGER /* TYPE OF COLUMN EQUIPSERVICE.SERVICEID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPSERVICE.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPSERVICE.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPSOFT_DEL (
    ID INTEGER /* TYPE OF COLUMN EQUIPSOFT.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPSOFT_INS (
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPSOFT.EQUIPID */,
    SOFTID INTEGER /* TYPE OF COLUMN EQUIPSOFT.SOFTID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPSOFT.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPSOFT.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN EQUIPSOFT.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE EQUIPSOFT_UPD (
    ID INTEGER /* TYPE OF COLUMN EQUIPSOFT.ID */,
    EQUIPID INTEGER /* TYPE OF COLUMN EQUIPSOFT.EQUIPID */,
    SOFTID INTEGER /* TYPE OF COLUMN EQUIPSOFT.SOFTID */,
    DAYOF DATE /* TYPE OF COLUMN EQUIPSOFT.DAYOF */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN EQUIPSOFT.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPTYPE_DEL (
    ID INTEGER /* TYPE OF COLUMN EQUIPTYPE.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE EQUIPTYPE_INS (
    NAME VARCHAR(30) /* TYPE OF COLUMN EQUIPTYPE.NAME */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN EQUIPTYPE.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE EQUIPTYPE_UPD (
    ID INTEGER /* TYPE OF COLUMN EQUIPTYPE.ID */,
    NAME VARCHAR(30) /* TYPE OF COLUMN EQUIPTYPE.NAME */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE ITMAN_DEL (
    ID INTEGER /* TYPE OF COLUMN ITMAN.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE ITMAN_INS (
    FM VARCHAR(30) /* TYPE OF COLUMN ITMAN.FM */,
    IM VARCHAR(30) /* TYPE OF COLUMN ITMAN.IM */,
    OT VARCHAR(30) /* TYPE OF COLUMN ITMAN.OT */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN ITMAN.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE ITMAN_UPD (
    ID INTEGER /* TYPE OF COLUMN ITMAN.ID */,
    FM VARCHAR(30) /* TYPE OF COLUMN ITMAN.FM */,
    IM VARCHAR(30) /* TYPE OF COLUMN ITMAN.IM */,
    OT VARCHAR(30) /* TYPE OF COLUMN ITMAN.OT */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE LAST_PLACE (
    ROOMID T_ID)
RETURNS (
    EQUIPID T_ID,
    EQUIPNAME VARCHAR(50) /* TYPE OF COLUMN EQUIP.NAME */,
    EQUIPTYPENAME VARCHAR(30) /* TYPE OF COLUMN EQUIPTYPE.NAME */,
    REGN VARCHAR(10) /* TYPE OF COLUMN EQUIP.REGN */,
    NOTE T_NOTE)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE ORDERS_DEL (
    ID INTEGER /* TYPE OF COLUMN ORDERS.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE ORDERS_INS (
    SOTRUDID INTEGER /* TYPE OF COLUMN ORDERS.SOTRUDID */,
    EQUIPID INTEGER /* TYPE OF COLUMN ORDERS.EQUIPID */,
    ROOMID INTEGER /* TYPE OF COLUMN ORDERS.ROOMID */,
    TASK VARCHAR(150) /* TYPE OF COLUMN ORDERS.TASK */,
    DAY1 DATE /* TYPE OF COLUMN ORDERS.DAY1 */,
    DAY2 DATE /* TYPE OF COLUMN ORDERS.DAY2 */,
    MARK INTEGER /* TYPE OF COLUMN ORDERS.MARK */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN ORDERS.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE ORDERS_SEL1
RETURNS (
    ID INTEGER /* TYPE OF COLUMN ORDERS.ID */,
    SOTRUDID INTEGER /* TYPE OF COLUMN ORDERS.SOTRUDID */,
    EQUIPID INTEGER /* TYPE OF COLUMN ORDERS.EQUIPID */,
    ROOMID INTEGER /* TYPE OF COLUMN ORDERS.ROOMID */,
    TASK VARCHAR(150) /* TYPE OF COLUMN ORDERS.TASK */,
    DAY1 DATE /* TYPE OF COLUMN ORDERS.DAY1 */,
    DAY2 DATE /* TYPE OF COLUMN ORDERS.DAY2 */,
    MARK INTEGER /* TYPE OF COLUMN ORDERS.MARK */,
    SOTRUDFIO T_FIO,
    EQUIPNAME T_EQUIPNAME,
    ROOMNO T_ROOMNO)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE ORDERS_UPD (
    ID INTEGER /* TYPE OF COLUMN ORDERS.ID */,
    SOTRUDID INTEGER /* TYPE OF COLUMN ORDERS.SOTRUDID */,
    EQUIPID INTEGER /* TYPE OF COLUMN ORDERS.EQUIPID */,
    ROOMID INTEGER /* TYPE OF COLUMN ORDERS.ROOMID */,
    TASK VARCHAR(150) /* TYPE OF COLUMN ORDERS.TASK */,
    DAY1 DATE /* TYPE OF COLUMN ORDERS.DAY1 */,
    DAY2 DATE /* TYPE OF COLUMN ORDERS.DAY2 */,
    MARK INTEGER /* TYPE OF COLUMN ORDERS.MARK */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE ROOM_DEL (
    ID INTEGER /* TYPE OF COLUMN ROOM.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE ROOM_INS (
    ROOMNO VARCHAR(10) /* TYPE OF COLUMN ROOM.ROOMNO */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN ROOM.NOTE */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN ROOM.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE ROOM_UPD (
    ID INTEGER /* TYPE OF COLUMN ROOM.ID */,
    ROOMNO VARCHAR(10) /* TYPE OF COLUMN ROOM.ROOMNO */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN ROOM.NOTE */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SERVICE_DEL (
    ID INTEGER /* TYPE OF COLUMN SERVICE.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SERVICE_INS (
    NAME VARCHAR(50) /* TYPE OF COLUMN SERVICE.NAME */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN SERVICE.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SERVICE_UPD (
    ID INTEGER /* TYPE OF COLUMN SERVICE.ID */,
    NAME VARCHAR(50) /* TYPE OF COLUMN SERVICE.NAME */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SOFT_DEL (
    ID INTEGER /* TYPE OF COLUMN SOFT.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SOFT_INS (
    NAME VARCHAR(50) /* TYPE OF COLUMN SOFT.NAME */,
    FREE INTEGER /* TYPE OF COLUMN SOFT.FREE */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN SOFT.NOTE */,
    LICENSES INTEGER /* TYPE OF COLUMN SOFT.LICENSES */,
    LASTDAY DATE /* TYPE OF COLUMN SOFT.LASTDAY */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN SOFT.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SOFT_INSTALLED (
    SOFTID T_ID)
RETURNS (
    CNT T_COUNT)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SOFT_UPD (
    ID INTEGER /* TYPE OF COLUMN SOFT.ID */,
    NAME VARCHAR(50) /* TYPE OF COLUMN SOFT.NAME */,
    FREE INTEGER /* TYPE OF COLUMN SOFT.FREE */,
    NOTE VARCHAR(100) /* TYPE OF COLUMN SOFT.NOTE */,
    LICENSES INTEGER /* TYPE OF COLUMN SOFT.LICENSES */,
    LASTDAY DATE /* TYPE OF COLUMN SOFT.LASTDAY */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SOTRUD_DEL (
    ID INTEGER /* TYPE OF COLUMN SOTRUD.ID */)
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SOTRUD_INS (
    FM VARCHAR(30) /* TYPE OF COLUMN SOTRUD.FM */,
    IM VARCHAR(30) /* TYPE OF COLUMN SOTRUD.IM */,
    OT VARCHAR(30) /* TYPE OF COLUMN SOTRUD.OT */)
RETURNS (
    ID INTEGER /* TYPE OF COLUMN SOTRUD.ID */)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE SOTRUD_UPD (
    ID INTEGER /* TYPE OF COLUMN SOTRUD.ID */,
    FM VARCHAR(30) /* TYPE OF COLUMN SOTRUD.FM */,
    IM VARCHAR(30) /* TYPE OF COLUMN SOTRUD.IM */,
    OT VARCHAR(30) /* TYPE OF COLUMN SOTRUD.OT */)
AS
BEGIN
  EXIT;
END^






SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CHANGEPLACE (
    ID       T_ID NOT NULL,
    EQUIPID  T_ID,
    ROOMID   T_ID,
    DAYOF    T_DATE,
    NOTE     T_NOTE
);

CREATE TABLE EQUIP (
    ID           T_ID NOT NULL,
    EQUIPTYPEID  T_ID,
    REGN         T_REGN,
    NAME         T_EQUIPNAME,
    DAYOF        T_DATE,
    NOTE         T_NOTE
);

CREATE TABLE EQUIPPART (
    ID           T_ID NOT NULL,
    EQUIPID      T_ID,
    EQUIPPARTID  T_ID,
    DAYOF        T_DATE,
    NOTE         T_NOTE
);

CREATE TABLE EQUIPSERVICE (
    ID         T_ID NOT NULL,
    ORDERID    T_ID,
    EQUIPID    T_ID,
    SERVICEID  T_ID,
    DAYOF      T_DATE,
    NOTE       T_NOTE
);

CREATE TABLE EQUIPSOFT (
    ID       T_ID NOT NULL,
    EQUIPID  T_ID,
    SOFTID   T_ID,
    DAYOF    T_DATE,
    NOTE     T_NOTE
);

CREATE TABLE EQUIPTYPE (
    ID    T_ID NOT NULL,
    NAME  T_EQUIPTYPENAME
);

CREATE TABLE ITMAN (
    ID  T_ID NOT NULL,
    FM  T_FM,
    IM  T_IM,
    OT  T_OT
);

CREATE TABLE ORDERS (
    ID        T_ID NOT NULL,
    SOTRUDID  T_ID,
    EQUIPID   T_ID,
    ROOMID    T_ID,
    TASK      T_TASK,
    DAY1      T_DATE,
    DAY2      T_DATE,
    MARK      T_MARK
);

CREATE TABLE ROOM (
    ID      T_ID NOT NULL,
    ROOMNO  T_ROOMNO,
    NOTE    T_NOTE
);

CREATE TABLE SERVICE (
    ID    T_ID NOT NULL,
    NAME  T_SERVICENAME
);

CREATE TABLE SOFT (
    ID        T_ID NOT NULL,
    NAME      T_SOFTNAME,
    FREE      T_BOOL,
    NOTE      T_NOTE,
    LICENSES  T_COUNT,
    LASTDAY   T_DATE
);

CREATE TABLE SOTRUD (
    ID  T_ID NOT NULL,
    FM  T_FM,
    IM  T_IM,
    OT  T_OT
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CHANGEPLACE ADD CONSTRAINT PK_CHANGEPLACE PRIMARY KEY (ID);
ALTER TABLE EQUIP ADD CONSTRAINT PK_EQUIP PRIMARY KEY (ID);
ALTER TABLE EQUIPPART ADD CONSTRAINT PK_EQUIPPART PRIMARY KEY (ID);
ALTER TABLE EQUIPSERVICE ADD CONSTRAINT PK_EQUIPSERVICE PRIMARY KEY (ID);
ALTER TABLE EQUIPSOFT ADD CONSTRAINT PK_EQUIPSOFT PRIMARY KEY (ID);
ALTER TABLE EQUIPTYPE ADD CONSTRAINT PK_EQUIPTYPE PRIMARY KEY (ID);
ALTER TABLE ITMAN ADD CONSTRAINT PK_ITMAN PRIMARY KEY (ID);
ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ID);
ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM PRIMARY KEY (ID);
ALTER TABLE SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY (ID);
ALTER TABLE SOFT ADD CONSTRAINT PK_SOFT PRIMARY KEY (ID);
ALTER TABLE SOTRUD ADD CONSTRAINT PK_SOTRUD PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CHANGEPLACE ADD CONSTRAINT FK_CHANGEPLACE_1 FOREIGN KEY (EQUIPID) REFERENCES EQUIP (ID);
ALTER TABLE CHANGEPLACE ADD CONSTRAINT FK_CHANGEPLACE_2 FOREIGN KEY (ROOMID) REFERENCES ROOM (ID);
ALTER TABLE EQUIP ADD CONSTRAINT FK_EQUIP_1 FOREIGN KEY (EQUIPTYPEID) REFERENCES EQUIPTYPE (ID);
ALTER TABLE EQUIPPART ADD CONSTRAINT FK_EQUIPPART_1 FOREIGN KEY (EQUIPID) REFERENCES EQUIP (ID);
ALTER TABLE EQUIPPART ADD CONSTRAINT FK_EQUIPPART_2 FOREIGN KEY (EQUIPPARTID) REFERENCES EQUIP (ID);
ALTER TABLE EQUIPSERVICE ADD CONSTRAINT FK_EQUIPSERVICE_1 FOREIGN KEY (EQUIPID) REFERENCES EQUIP (ID);
ALTER TABLE EQUIPSERVICE ADD CONSTRAINT FK_EQUIPSERVICE_2 FOREIGN KEY (SERVICEID) REFERENCES SERVICE (ID);
ALTER TABLE EQUIPSOFT ADD CONSTRAINT FK_EQUIPSOFT_1 FOREIGN KEY (EQUIPID) REFERENCES EQUIP (ID);
ALTER TABLE EQUIPSOFT ADD CONSTRAINT FK_EQUIPSOFT_2 FOREIGN KEY (SOFTID) REFERENCES SOFT (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CHANGEPLACE_BI */
CREATE TRIGGER CHANGEPLACE_BI FOR CHANGEPLACE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  -- ≈сли новое значение ключевого пол€ пусто
  if (new.id is null) then
  -- увеличить текущее значение генератора на 1
  -- и присвоить новому значению ключевого пол€ 
    new.id = gen_id(gen_changeplace_id,1);
end
^

/* Trigger: EQUIPPART_BI */
CREATE TRIGGER EQUIPPART_BI FOR EQUIPPART
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_equippart_id,1);
end
^

/* Trigger: EQUIPSERVICE_BI0 */
CREATE TRIGGER EQUIPSERVICE_BI0 FOR EQUIPSERVICE
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_equipservice_id;
end
^

/* Trigger: EQUIPSOFT_BI */
CREATE TRIGGER EQUIPSOFT_BI FOR EQUIPSOFT
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_equipSoft_id,1);
end
^

/* Trigger: EQUIPTYPE_BI0 */
CREATE TRIGGER EQUIPTYPE_BI0 FOR EQUIPTYPE
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_equiptype_id;
end
^

/* Trigger: EQUIP_BI0 */
CREATE TRIGGER EQUIP_BI0 FOR EQUIP
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_equip_id;
end
^

/* Trigger: ITMAN_BI0 */
CREATE TRIGGER ITMAN_BI0 FOR ITMAN
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_ITMAN_id;
end
^

/* Trigger: ORDERS_BI */
CREATE TRIGGER ORDERS_BI FOR ORDERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_orders_id,1);
end
^

/* Trigger: ROOM_BI0 */
CREATE TRIGGER ROOM_BI0 FOR ROOM
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_room_id;
end
^

/* Trigger: SERVICE_BI0 */
CREATE TRIGGER SERVICE_BI0 FOR SERVICE
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_Service_id;
end
^

/* Trigger: SOFT_BI0 */
CREATE TRIGGER SOFT_BI0 FOR SOFT
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_Soft_id;
end
^

/* Trigger: SOTRUD_BI0 */
CREATE TRIGGER SOTRUD_BI0 FOR SOTRUD
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = next value for gen_SOTRUD_id;
end
^

SET TERM ; ^



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE CHANGEPLACE_DEL (
    ID TYPE OF COLUMN CHANGEPLACE.ID)
AS
begin
  -- ”далить все строки из таблицы
  delete from changeplace -- 
  -- ƒл€ которых значение »ƒ строки равно значению
  -- передаваемого параметра
  where (id = :id);
end^


ALTER PROCEDURE CHANGEPLACE_INS (
    EQUIPID TYPE OF COLUMN CHANGEPLACE.EQUIPID,
    ROOMID TYPE OF COLUMN CHANGEPLACE.ROOMID,
    DAYOF TYPE OF COLUMN CHANGEPLACE.DAYOF,
    NOTE TYPE OF COLUMN CHANGEPLACE.NOTE)
RETURNS (
    ID TYPE OF COLUMN CHANGEPLACE.ID)
AS
begin
  -- ¬ставить строку
  insert into changeplace (
    equipid,
    roomid,
    dayof,
    note)
  values ( -- со значени€ми
    :equipid,
    :roomid,
    :dayof,
    :note)
  returning changeplace.id into :id;
  -- и возвратить новое »ƒ строки
  suspend;
end^


ALTER PROCEDURE CHANGEPLACE_UPD (
    ID TYPE OF COLUMN CHANGEPLACE.ID,
    EQUIPID TYPE OF COLUMN CHANGEPLACE.EQUIPID,
    ROOMID TYPE OF COLUMN CHANGEPLACE.ROOMID,
    DAYOF TYPE OF COLUMN CHANGEPLACE.DAYOF,
    NOTE TYPE OF COLUMN CHANGEPLACE.NOTE)
AS
begin
  update changeplace
  set equipid = :equipid,
      roomid = :roomid,
      dayof = :dayof,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE EQUIP_DEL (
    ID TYPE OF COLUMN EQUIP.ID)
AS
begin
  delete from equip
  where (id = :id);
end^


ALTER PROCEDURE EQUIP_INS (
    EQUIPTYPEID TYPE OF COLUMN EQUIP.EQUIPTYPEID,
    REGN TYPE OF COLUMN EQUIP.REGN,
    NAME TYPE OF COLUMN EQUIP.NAME,
    DAYOF TYPE OF COLUMN EQUIP.DAYOF,
    NOTE TYPE OF COLUMN EQUIP.NOTE)
RETURNS (
    ID TYPE OF COLUMN EQUIP.ID)
AS
begin
  insert into equip (
    equiptypeid,
    regn,
    name,
    dayof,
    note)
  values (
    :equiptypeid,
    :regn,
    :name,
    :dayof,
    :note)
  returning equip.id into :id;
  suspend;
end^


ALTER PROCEDURE EQUIP_UPD (
    ID TYPE OF COLUMN EQUIP.ID,
    EQUIPTYPEID TYPE OF COLUMN EQUIP.EQUIPTYPEID,
    REGN TYPE OF COLUMN EQUIP.REGN,
    NAME TYPE OF COLUMN EQUIP.NAME,
    DAYOF TYPE OF COLUMN EQUIP.DAYOF,
    NOTE TYPE OF COLUMN EQUIP.NOTE)
AS
begin
  update equip
  set equiptypeid = :equiptypeid,
      regn = :regn,
      name = :name,
      dayof = :dayof,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE EQUIPPART_DEL (
    ID TYPE OF COLUMN EQUIPPART.ID)
AS
begin
  delete from equippart
  where (id = :id);
end^


ALTER PROCEDURE EQUIPPART_INS (
    EQUIPID TYPE OF COLUMN EQUIPPART.EQUIPID,
    EQUIPPARTID TYPE OF COLUMN EQUIPPART.EQUIPPARTID,
    DAYOF TYPE OF COLUMN EQUIPPART.DAYOF,
    NOTE TYPE OF COLUMN EQUIPPART.NOTE)
RETURNS (
    ID TYPE OF COLUMN EQUIPPART.ID)
AS
begin
  insert into equippart (
    equipid,
    equippartid,
    dayof,
    note)
  values (
    :equipid,
    :equippartid,
    :dayof,
    :note)
  returning equippart.id into :id;
  suspend;
end^


ALTER PROCEDURE EQUIPPART_UPD (
    ID TYPE OF COLUMN EQUIPPART.ID,
    EQUIPID TYPE OF COLUMN EQUIPPART.EQUIPID,
    EQUIPPARTID TYPE OF COLUMN EQUIPPART.EQUIPPARTID,
    DAYOF TYPE OF COLUMN EQUIPPART.DAYOF,
    NOTE TYPE OF COLUMN EQUIPPART.NOTE)
AS
begin
  update equippart
  set equipid = :equipid,
      equippartid = :equippartid,
      dayof = :dayof,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE EQUIPSERVICE_DEL (
    ID TYPE OF COLUMN EQUIPSERVICE.ID)
AS
begin
  delete from equipservice
  where (id = :id);
end^


ALTER PROCEDURE EQUIPSERVICE_INS (
    ORDERID TYPE OF COLUMN EQUIPSERVICE.ORDERID,
    EQUIPID TYPE OF COLUMN EQUIPSERVICE.EQUIPID,
    SERVICEID TYPE OF COLUMN EQUIPSERVICE.SERVICEID,
    DAYOF TYPE OF COLUMN EQUIPSERVICE.DAYOF,
    NOTE TYPE OF COLUMN EQUIPSERVICE.NOTE)
RETURNS (
    ID TYPE OF COLUMN EQUIPSERVICE.ID)
AS
begin
  insert into equipService (
    OrderId,
    equipid,
    Serviceid,
    dayof,
    note)
  values (
    :OrderId,
    :equipid,
    :Serviceid,
    :dayof,
    :note)
  returning equipService.id into :id;
  suspend;
end^


ALTER PROCEDURE EQUIPSERVICE_UPD (
    ID TYPE OF COLUMN EQUIPSERVICE.ID,
    ORDERID TYPE OF COLUMN EQUIPSERVICE.ORDERID,
    EQUIPID TYPE OF COLUMN EQUIPSERVICE.EQUIPID,
    SERVICEID TYPE OF COLUMN EQUIPSERVICE.SERVICEID,
    DAYOF TYPE OF COLUMN EQUIPSERVICE.DAYOF,
    NOTE TYPE OF COLUMN EQUIPSERVICE.NOTE)
AS
begin
  update equipService
  set orderid = :orderid,
      equipid = :equipid,
      Serviceid = :Serviceid,
      dayof = :dayof,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE EQUIPSOFT_DEL (
    ID TYPE OF COLUMN EQUIPSOFT.ID)
AS
begin
  delete from equipSoft
  where (id = :id);
end^


ALTER PROCEDURE EQUIPSOFT_INS (
    EQUIPID TYPE OF COLUMN EQUIPSOFT.EQUIPID,
    SOFTID TYPE OF COLUMN EQUIPSOFT.SOFTID,
    DAYOF TYPE OF COLUMN EQUIPSOFT.DAYOF,
    NOTE TYPE OF COLUMN EQUIPSOFT.NOTE)
RETURNS (
    ID TYPE OF COLUMN EQUIPSOFT.ID)
AS
begin
  insert into equipSoft (
    equipid,
    Softid,
    dayof,
    note)
  values (
    :equipid,
    :Softid,
    :dayof,
    :note)
  returning equipSoft.id into :id;
  suspend;
end^


ALTER PROCEDURE EQUIPSOFT_UPD (
    ID TYPE OF COLUMN EQUIPSOFT.ID,
    EQUIPID TYPE OF COLUMN EQUIPSOFT.EQUIPID,
    SOFTID TYPE OF COLUMN EQUIPSOFT.SOFTID,
    DAYOF TYPE OF COLUMN EQUIPSOFT.DAYOF,
    NOTE TYPE OF COLUMN EQUIPSOFT.NOTE)
AS
begin
  update equipSoft
  set equipid = :equipid,
      Softid = :Softid,
      dayof = :dayof,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE EQUIPTYPE_DEL (
    ID TYPE OF COLUMN EQUIPTYPE.ID)
AS
begin
  delete from equiptype
  where (id = :id);
end^


ALTER PROCEDURE EQUIPTYPE_INS (
    NAME TYPE OF COLUMN EQUIPTYPE.NAME)
RETURNS (
    ID TYPE OF COLUMN EQUIPTYPE.ID)
AS
begin
  insert into equiptype (
    name)
  values (
    :name)
  returning equiptype.id into :id;
  suspend;
end^


ALTER PROCEDURE EQUIPTYPE_UPD (
    ID TYPE OF COLUMN EQUIPTYPE.ID,
    NAME TYPE OF COLUMN EQUIPTYPE.NAME)
AS
begin
  update equiptype
  set name = :name
  where (id = :id);
end^


ALTER PROCEDURE ITMAN_DEL (
    ID TYPE OF COLUMN ITMAN.ID)
AS
begin
  delete from ITMAN
  where (id = :id);
end^


ALTER PROCEDURE ITMAN_INS (
    FM TYPE OF COLUMN ITMAN.FM,
    IM TYPE OF COLUMN ITMAN.IM,
    OT TYPE OF COLUMN ITMAN.OT)
RETURNS (
    ID TYPE OF COLUMN ITMAN.ID)
AS
begin
  insert into ITMAN (
    fm, im, ot)
  values (
    :fm, :im, :ot)
  returning ITMAN.id into :id;
  suspend;
end^


ALTER PROCEDURE ITMAN_UPD (
    ID TYPE OF COLUMN ITMAN.ID,
    FM TYPE OF COLUMN ITMAN.FM,
    IM TYPE OF COLUMN ITMAN.IM,
    OT TYPE OF COLUMN ITMAN.OT)
AS
begin
  update ITMAN
  set fm = :fm,
      im = :im,
      ot = :ot
  where (id = :id);
end^


ALTER PROCEDURE LAST_PLACE (
    ROOMID T_ID)
RETURNS (
    EQUIPID T_ID,
    EQUIPNAME TYPE OF COLUMN EQUIP.NAME,
    EQUIPTYPENAME TYPE OF COLUMN EQUIPTYPE.NAME,
    REGN TYPE OF COLUMN EQUIP.REGN,
    NOTE T_NOTE)
AS
declare variable THISROOMID T_ID;
declare variable MAXDAY T_DATE;
begin
  /* ¬о внешнем запросе вычисл€ем последние даты 
     по каждой единице оборудовани€ */

  for select cp1.equipid, max(cp1.dayof)
    from changeplace cp1
    group by cp1.equipid
    having max(cp1.dayof) =
    (
    /* в подзапросе вы€сн€ем, €вл€етс€ ли аудитори€,
       в которую было последнее перемещение, "нашей" аудиторией */
      select max(cp2.dayof)
      from changeplace cp2
      where (cp2.roomid = :roomid) and (cp2.equipid = cp1.equipid)
      group by cp2.equipid
    )
    into :equipid, :maxday
  do begin
    select equip.name, et.name, equip.regn, equip.note
    from equip
    left outer join equiptype et on equip.equiptypeid = et.id
    where equip.id = :equipid
    into :equipname, :equiptypename, :regn, :note;
    suspend;
  end
end^


ALTER PROCEDURE ORDERS_DEL (
    ID TYPE OF COLUMN ORDERS.ID)
AS
begin
  delete from orders
  where (id = :id);
end^


ALTER PROCEDURE ORDERS_INS (
    SOTRUDID TYPE OF COLUMN ORDERS.SOTRUDID,
    EQUIPID TYPE OF COLUMN ORDERS.EQUIPID,
    ROOMID TYPE OF COLUMN ORDERS.ROOMID,
    TASK TYPE OF COLUMN ORDERS.TASK,
    DAY1 TYPE OF COLUMN ORDERS.DAY1,
    DAY2 TYPE OF COLUMN ORDERS.DAY2,
    MARK TYPE OF COLUMN ORDERS.MARK)
RETURNS (
    ID TYPE OF COLUMN ORDERS.ID)
AS
begin
  insert into orders (
    sotrudid,
    equipid,
    roomid,
    task,
    day1,
    day2,
    mark)
  values (
    :sotrudid,
    :equipid,
    :roomid,
    :task,
    :day1,
    :day2,
    :mark)
  returning orders.id into :id;
  suspend;
end^


ALTER PROCEDURE ORDERS_SEL1
RETURNS (
    ID TYPE OF COLUMN ORDERS.ID,
    SOTRUDID TYPE OF COLUMN ORDERS.SOTRUDID,
    EQUIPID TYPE OF COLUMN ORDERS.EQUIPID,
    ROOMID TYPE OF COLUMN ORDERS.ROOMID,
    TASK TYPE OF COLUMN ORDERS.TASK,
    DAY1 TYPE OF COLUMN ORDERS.DAY1,
    DAY2 TYPE OF COLUMN ORDERS.DAY2,
    MARK TYPE OF COLUMN ORDERS.MARK,
    SOTRUDFIO T_FIO,
    EQUIPNAME T_EQUIPNAME,
    ROOMNO T_ROOMNO)
AS
begin
  for select
    orders.id, orders.sotrudid, orders.equipid, orders.roomid, task,
    orders.day1, orders.day2, orders.mark,
    sotrud.fm || ' ' || sotrud.im || ' ' || sotrud.ot,
    equip.name,
    room.roomno
      from orders
      left outer join sotrud on orders.sotrudid = sotrud.id
      left outer join equip on orders.equipid = equip.id
      left outer join room on orders.roomid = room.id
      into
        :id, :sotrudid, :equipid, :roomid, :task, :day1, :day2, :mark,
        :sotrudfio, :equipname, :roomno
  do
  begin
    suspend;
  end
end^


ALTER PROCEDURE ORDERS_UPD (
    ID TYPE OF COLUMN ORDERS.ID,
    SOTRUDID TYPE OF COLUMN ORDERS.SOTRUDID,
    EQUIPID TYPE OF COLUMN ORDERS.EQUIPID,
    ROOMID TYPE OF COLUMN ORDERS.ROOMID,
    TASK TYPE OF COLUMN ORDERS.TASK,
    DAY1 TYPE OF COLUMN ORDERS.DAY1,
    DAY2 TYPE OF COLUMN ORDERS.DAY2,
    MARK TYPE OF COLUMN ORDERS.MARK)
AS
begin
  update orders
  set sotrudid = :sotrudid,
      equipid = :equipid,
      roomid = :roomid,
      task = :task,
      day1 = :day1,
      day2 = :day2,
      mark = :mark
  where (id = :id);
end^


ALTER PROCEDURE ROOM_DEL (
    ID TYPE OF COLUMN ROOM.ID)
AS
begin
  delete from room
  where (id = :id);
end^


ALTER PROCEDURE ROOM_INS (
    ROOMNO TYPE OF COLUMN ROOM.ROOMNO,
    NOTE TYPE OF COLUMN ROOM.NOTE)
RETURNS (
    ID TYPE OF COLUMN ROOM.ID)
AS
begin
  insert into room (
    roomno,
    note)
  values (
    :roomno,
    :note)
  returning room.id into :id;
  suspend;
end^


ALTER PROCEDURE ROOM_UPD (
    ID TYPE OF COLUMN ROOM.ID,
    ROOMNO TYPE OF COLUMN ROOM.ROOMNO,
    NOTE TYPE OF COLUMN ROOM.NOTE)
AS
begin
  update room
  set roomno = :roomno,
      note = :note
  where (id = :id);
end^


ALTER PROCEDURE SERVICE_DEL (
    ID TYPE OF COLUMN SERVICE.ID)
AS
begin
  delete from Service
  where (id = :id);
end^


ALTER PROCEDURE SERVICE_INS (
    NAME TYPE OF COLUMN SERVICE.NAME)
RETURNS (
    ID TYPE OF COLUMN SERVICE.ID)
AS
begin
  insert into Service (
    name)
  values (
    :name)
  returning Service.id into :id;
  suspend;
end^


ALTER PROCEDURE SERVICE_UPD (
    ID TYPE OF COLUMN SERVICE.ID,
    NAME TYPE OF COLUMN SERVICE.NAME)
AS
begin
  update Service
  set name = :name
  where (id = :id);
end^


ALTER PROCEDURE SOFT_DEL (
    ID TYPE OF COLUMN SOFT.ID)
AS
begin
  delete from soft
  where (id = :id);
end^


ALTER PROCEDURE SOFT_INS (
    NAME TYPE OF COLUMN SOFT.NAME,
    FREE TYPE OF COLUMN SOFT.FREE,
    NOTE TYPE OF COLUMN SOFT.NOTE,
    LICENSES TYPE OF COLUMN SOFT.LICENSES,
    LASTDAY TYPE OF COLUMN SOFT.LASTDAY)
RETURNS (
    ID TYPE OF COLUMN SOFT.ID)
AS
begin
  insert into soft (
    name, free, note, licenses, lastday)
  values (
    :name, :free, :note, :licenses, :lastday)
  returning soft.id into :id;
  suspend;
end^


ALTER PROCEDURE SOFT_INSTALLED (
    SOFTID T_ID)
RETURNS (
    CNT T_COUNT)
AS
begin
  select count(es.dayof)
  from equipsoft es
  where (es.softid = :softid)
  into :cnt;
  suspend;
end^


ALTER PROCEDURE SOFT_UPD (
    ID TYPE OF COLUMN SOFT.ID,
    NAME TYPE OF COLUMN SOFT.NAME,
    FREE TYPE OF COLUMN SOFT.FREE,
    NOTE TYPE OF COLUMN SOFT.NOTE,
    LICENSES TYPE OF COLUMN SOFT.LICENSES,
    LASTDAY TYPE OF COLUMN SOFT.LASTDAY)
AS
begin
  update soft
  set name = :name,
      free = :free,
      note = :note,
      licenses = :licenses,
      lastday = :lastday
  where (id = :id);
end^


ALTER PROCEDURE SOTRUD_DEL (
    ID TYPE OF COLUMN SOTRUD.ID)
AS
begin
  delete from SOTRUD
  where (id = :id);
end^


ALTER PROCEDURE SOTRUD_INS (
    FM TYPE OF COLUMN SOTRUD.FM,
    IM TYPE OF COLUMN SOTRUD.IM,
    OT TYPE OF COLUMN SOTRUD.OT)
RETURNS (
    ID TYPE OF COLUMN SOTRUD.ID)
AS
begin
  insert into SOTRUD (
    fm, im, ot)
  values (
    :fm, :im, :ot)
  returning SOTRUD.id into :id;
  suspend;
end^


ALTER PROCEDURE SOTRUD_UPD (
    ID TYPE OF COLUMN SOTRUD.ID,
    FM TYPE OF COLUMN SOTRUD.FM,
    IM TYPE OF COLUMN SOTRUD.IM,
    OT TYPE OF COLUMN SOTRUD.OT)
AS
begin
  update SOTRUD
  set fm = :fm,
      im = :im,
      ot = :ot
  where (id = :id);
end^



SET TERM ; ^
