from PyQt5 import QtCore, QtGui, QtWidgets


class UiWindow(object):
    def __init__(self, window):
        super(UiWindow, self).__init__()
        window.setObjectName("MainWindow")
        window.resize(743, 367)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Изображения/free-icon-binder-4624080.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        window.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.tabWidget.setObjectName("tabWidget")
        self.bachelor_course = QtWidgets.QWidget()
        self.bachelor_course.setStyleSheet("")
        self.bachelor_course.setObjectName("bachelor_course")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.bachelor_course)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grid_layout_b = QtWidgets.QGridLayout()
        self.grid_layout_b.setObjectName("grid_layout_b")
        self.foe_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.foe_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_b.setFont(font)
        self.foe_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_b.setObjectName("foe_label_b")
        self.grid_layout_b.addWidget(self.foe_label_b, 0, 0, 1, 1)
        self.foe_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_b.setFont(font)
        self.foe_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_b.setObjectName("foe_combo_box_b")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.foe_combo_box_b, 1, 0, 1, 1)
        self.direction_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.direction_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_b.setFont(font)
        self.direction_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_b.setObjectName("direction_label_b")
        self.grid_layout_b.addWidget(self.direction_label_b, 0, 1, 1, 1)
        self.year_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_b.setFont(font)
        self.year_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_b.setObjectName("year_combo_box_b")
        self.year_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.year_combo_box_b, 1, 2, 1, 1)
        self.year_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.year_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_b.setFont(font)
        self.year_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_b.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_b.setObjectName("year_label_b")
        self.grid_layout_b.addWidget(self.year_label_b, 0, 2, 1, 1)
        self.month_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_b.setFont(font)
        self.month_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_b.setObjectName("month_combo_box_b")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.month_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.month_combo_box_b, 1, 3, 1, 1)
        self.direction_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_b.setFont(font)
        self.direction_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_b.setObjectName("direction_combo_box_b")
        self.direction_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.direction_combo_box_b, 1, 1, 1, 1)
        self.month_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.month_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_b.setFont(font)
        self.month_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_b.setObjectName("month_label_b")
        self.grid_layout_b.addWidget(self.month_label_b, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.grid_layout_b, 0, 0, 1, 1)
        self.table_widget_b = QtWidgets.QTableWidget(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_b.setFont(font)
        self.table_widget_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_b.setObjectName("table_widget_b")
        self.table_widget_b.setColumnCount(0)
        self.table_widget_b.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_widget_b, 1, 0, 1, 1)
        self.tabWidget.addTab(self.bachelor_course, "")
        self.master_course = QtWidgets.QWidget()
        self.master_course.setObjectName("master_course")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.master_course)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grid_layout_m = QtWidgets.QGridLayout()
        self.grid_layout_m.setObjectName("grid_layout_m")
        self.foe_label_m = QtWidgets.QLabel(self.master_course)
        self.foe_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_m.setFont(font)
        self.foe_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_m.setObjectName("foe_label_m")
        self.grid_layout_m.addWidget(self.foe_label_m, 0, 0, 1, 1)
        self.foe_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_m.setFont(font)
        self.foe_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_m.setObjectName("foe_combo_box_m")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.foe_combo_box_m, 1, 0, 1, 1)
        self.direction_label_m = QtWidgets.QLabel(self.master_course)
        self.direction_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_m.setFont(font)
        self.direction_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_m.setObjectName("direction_label_m")
        self.grid_layout_m.addWidget(self.direction_label_m, 0, 1, 1, 1)
        self.year_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_m.setFont(font)
        self.year_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_m.setObjectName("year_combo_box_m")
        self.year_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.year_combo_box_m, 1, 2, 1, 1)
        self.year_label_m = QtWidgets.QLabel(self.master_course)
        self.year_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_m.setFont(font)
        self.year_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_m.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_m.setObjectName("year_label_m")
        self.grid_layout_m.addWidget(self.year_label_m, 0, 2, 1, 1)
        self.month_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_m.setFont(font)
        self.month_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_m.setObjectName("month_combo_box_m")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.month_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.month_combo_box_m, 1, 3, 1, 1)
        self.direction_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_m.setFont(font)
        self.direction_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_m.setObjectName("direction_combo_box_m")
        self.direction_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.direction_combo_box_m, 1, 1, 1, 1)
        self.month_label_m = QtWidgets.QLabel(self.master_course)
        self.month_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_m.setFont(font)
        self.month_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_m.setObjectName("month_label_m")
        self.grid_layout_m.addWidget(self.month_label_m, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.grid_layout_m, 0, 0, 1, 1)
        self.table_widget_m = QtWidgets.QTableWidget(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_m.setFont(font)
        self.table_widget_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_m.setObjectName("table_widget_m")
        self.table_widget_m.setColumnCount(0)
        self.table_widget_m.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_widget_m, 1, 0, 1, 1)
        self.tabWidget.addTab(self.master_course, "")
        self.specialist_degree = QtWidgets.QWidget()
        self.specialist_degree.setObjectName("specialist_degree")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.specialist_degree)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.grid_layout_s = QtWidgets.QGridLayout()
        self.grid_layout_s.setObjectName("grid_layout_s")
        self.foe_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.foe_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_s.setFont(font)
        self.foe_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_s.setObjectName("foe_label_s")
        self.grid_layout_s.addWidget(self.foe_label_s, 0, 0, 1, 1)
        self.foe_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_s.setFont(font)
        self.foe_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_s.setObjectName("foe_combo_box_s")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.foe_combo_box_s, 1, 0, 1, 1)
        self.direction_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.direction_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_s.setFont(font)
        self.direction_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_s.setObjectName("direction_label_s")
        self.grid_layout_s.addWidget(self.direction_label_s, 0, 1, 1, 1)
        self.year_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_s.setFont(font)
        self.year_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_s.setObjectName("year_combo_box_s")
        self.year_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.year_combo_box_s, 1, 2, 1, 1)
        self.year_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.year_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_s.setFont(font)
        self.year_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_s.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_s.setObjectName("year_label_s")
        self.grid_layout_s.addWidget(self.year_label_s, 0, 2, 1, 1)
        self.month_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_s.setFont(font)
        self.month_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_s.setObjectName("month_combo_box_s")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.month_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.month_combo_box_s, 1, 3, 1, 1)
        self.direction_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_s.setFont(font)
        self.direction_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_s.setObjectName("direction_combo_box_s")
        self.direction_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.direction_combo_box_s, 1, 1, 1, 1)
        self.month_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.month_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_s.setFont(font)
        self.month_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_s.setObjectName("month_label_s")
        self.grid_layout_s.addWidget(self.month_label_s, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.grid_layout_s, 0, 0, 1, 1)
        self.table_widget_s = QtWidgets.QTableWidget(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_s.setFont(font)
        self.table_widget_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_s.setObjectName("table_widget_s")
        self.table_widget_s.setColumnCount(0)
        self.table_widget_s.setRowCount(0)
        self.gridLayout_8.addWidget(self.table_widget_s, 1, 0, 1, 1)
        self.tabWidget.addTab(self.specialist_degree, "")
        self.CSET = QtWidgets.QWidget()
        self.CSET.setObjectName("CSET")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.CSET)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.grid_layout_CSET = QtWidgets.QGridLayout()
        self.grid_layout_CSET.setObjectName("grid_layout_CSET")
        self.foe_label_CSET = QtWidgets.QLabel(self.CSET)
        self.foe_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_CSET.setFont(font)
        self.foe_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_CSET.setObjectName("foe_label_CSET")
        self.grid_layout_CSET.addWidget(self.foe_label_CSET, 0, 0, 1, 1)
        self.foe_combo_box_CSET = QtWidgets.QComboBox(self.CSET)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_CSET.setFont(font)
        self.foe_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_CSET.setObjectName("foe_combo_box_CSET")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.foe_combo_box_CSET, 1, 0, 1, 1)
        self.direction_label_CSET = QtWidgets.QLabel(self.CSET)
        self.direction_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_CSET.setFont(font)
        self.direction_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_CSET.setObjectName("direction_label_CSET")
        self.grid_layout_CSET.addWidget(self.direction_label_CSET, 0, 1, 1, 1)
        self.year_combo_box_CSET = QtWidgets.QComboBox(self.CSET)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_CSET.setFont(font)
        self.year_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_CSET.setObjectName("year_combo_box_CSET")
        self.year_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.year_combo_box_CSET, 1, 2, 1, 1)
        self.year_label_CSET = QtWidgets.QLabel(self.CSET)
        self.year_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_CSET.setFont(font)
        self.year_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_CSET.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_CSET.setObjectName("year_label_CSET")
        self.grid_layout_CSET.addWidget(self.year_label_CSET, 0, 2, 1, 1)
        self.month_combo_box_CSET = QtWidgets.QComboBox(self.CSET)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_CSET.setFont(font)
        self.month_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_CSET.setObjectName("month_combo_box_CSET")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.month_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.month_combo_box_CSET, 1, 3, 1, 1)
        self.direction_combo_box_CSET = QtWidgets.QComboBox(self.CSET)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_CSET.setFont(font)
        self.direction_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_CSET.setObjectName("direction_combo_box_CSET")
        self.direction_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.direction_combo_box_CSET, 1, 1, 1, 1)
        self.month_label_CSET = QtWidgets.QLabel(self.CSET)
        self.month_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_CSET.setFont(font)
        self.month_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_CSET.setObjectName("month_label_CSET")
        self.grid_layout_CSET.addWidget(self.month_label_CSET, 0, 3, 1, 1)
        self.gridLayout_10.addLayout(self.grid_layout_CSET, 0, 0, 1, 1)
        self.table_widget_CSET = QtWidgets.QTableWidget(self.CSET)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_CSET.setFont(font)
        self.table_widget_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_CSET.setObjectName("table_widget_CSET")
        self.table_widget_CSET.setColumnCount(0)
        self.table_widget_CSET.setRowCount(0)
        self.gridLayout_10.addWidget(self.table_widget_CSET, 1, 0, 1, 1)
        self.tabWidget.addTab(self.CSET, "")
        self.TSTD = QtWidgets.QWidget()
        self.TSTD.setObjectName("TSTD")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.TSTD)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.grid_layout_TSTD = QtWidgets.QGridLayout()
        self.grid_layout_TSTD.setObjectName("grid_layout_TSTD")
        self.foe_label_TSTD = QtWidgets.QLabel(self.TSTD)
        self.foe_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_TSTD.setFont(font)
        self.foe_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_TSTD.setObjectName("foe_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.foe_label_TSTD, 0, 0, 1, 1)
        self.foe_combo_box_TSTD = QtWidgets.QComboBox(self.TSTD)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_TSTD.setFont(font)
        self.foe_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_TSTD.setObjectName("foe_combo_box_TSTD")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.foe_combo_box_TSTD, 1, 0, 1, 1)
        self.direction_label_TSTD = QtWidgets.QLabel(self.TSTD)
        self.direction_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_TSTD.setFont(font)
        self.direction_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_TSTD.setObjectName("direction_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.direction_label_TSTD, 0, 1, 1, 1)
        self.year_combo_box_TSTD = QtWidgets.QComboBox(self.TSTD)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_TSTD.setFont(font)
        self.year_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_TSTD.setObjectName("year_combo_box_TSTD")
        self.year_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.year_combo_box_TSTD, 1, 2, 1, 1)
        self.year_label_TSTD = QtWidgets.QLabel(self.TSTD)
        self.year_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_TSTD.setFont(font)
        self.year_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_TSTD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_TSTD.setObjectName("year_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.year_label_TSTD, 0, 2, 1, 1)
        self.month_combo_box_TSTD = QtWidgets.QComboBox(self.TSTD)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_TSTD.setFont(font)
        self.month_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_TSTD.setObjectName("month_combo_box_TSTD")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.month_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.month_combo_box_TSTD, 1, 3, 1, 1)
        self.direction_combo_box_TSTD = QtWidgets.QComboBox(self.TSTD)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_TSTD.setFont(font)
        self.direction_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_TSTD.setObjectName("direction_combo_box_TSTD")
        self.direction_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.direction_combo_box_TSTD, 1, 1, 1, 1)
        self.month_label_TSTD = QtWidgets.QLabel(self.TSTD)
        self.month_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_TSTD.setFont(font)
        self.month_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_TSTD.setObjectName("month_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.month_label_TSTD, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.grid_layout_TSTD, 0, 0, 1, 1)
        self.table_widget_TSTD = QtWidgets.QTableWidget(self.TSTD)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_TSTD.setFont(font)
        self.table_widget_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_TSTD.setObjectName("table_widget_TSTD")
        self.table_widget_TSTD.setColumnCount(0)
        self.table_widget_TSTD.setRowCount(0)
        self.gridLayout_12.addWidget(self.table_widget_TSTD, 1, 0, 1, 1)
        self.tabWidget.addTab(self.TSTD, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.last_month_label = QtWidgets.QLabel(self.page_2)
        self.last_month_label.setObjectName("last_month_label")
        self.gridLayout_2.addWidget(self.last_month_label, 0, 0, 1, 1)
        self.table_widget_last_month = QtWidgets.QTableWidget(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_last_month.setFont(font)
        self.table_widget_last_month.setObjectName("table_widget_last_month")
        self.table_widget_last_month.setColumnCount(0)
        self.table_widget_last_month.setRowCount(0)
        self.table_widget_last_month.horizontalHeader().setMinimumSectionSize(47)
        self.table_widget_last_month.verticalHeader().setDefaultSectionSize(31)
        self.table_widget_last_month.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout_2.addWidget(self.table_widget_last_month, 1, 0, 1, 1)
        self.last_year_label = QtWidgets.QLabel(self.page_2)
        self.last_year_label.setObjectName("last_year_label")
        self.gridLayout_2.addWidget(self.last_year_label, 2, 0, 1, 1)
        self.table_widget_last_year = QtWidgets.QTableWidget(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_widget_last_year.setFont(font)
        self.table_widget_last_year.setObjectName("table_widget_last_year")
        self.table_widget_last_year.setColumnCount(0)
        self.table_widget_last_year.setRowCount(0)
        self.table_widget_last_year.horizontalHeader().setMinimumSectionSize(47)
        self.table_widget_last_year.verticalHeader().setDefaultSectionSize(31)
        self.table_widget_last_year.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout_2.addWidget(self.table_widget_last_year, 3, 0, 1, 1)
        self.back_button = QtWidgets.QPushButton(self.page_2)
        self.back_button.setObjectName("back_button")
        self.gridLayout_2.addWidget(self.back_button, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(window)
        self.toolBar.setObjectName("toolBar")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslate_ui(window)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "StudInStudOut"))
        self.foe_label_b.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_b.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_b.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_b.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_b.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_b.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.month_combo_box_b.setItemText(1, _translate("MainWindow", "Январь"))
        self.month_combo_box_b.setItemText(2, _translate("MainWindow", "Февраль"))
        self.month_combo_box_b.setItemText(3, _translate("MainWindow", "Март"))
        self.month_combo_box_b.setItemText(4, _translate("MainWindow", "Апрель"))
        self.month_combo_box_b.setItemText(5, _translate("MainWindow", "Май"))
        self.month_combo_box_b.setItemText(6, _translate("MainWindow", "Июнь"))
        self.month_combo_box_b.setItemText(7, _translate("MainWindow", "Июль"))
        self.month_combo_box_b.setItemText(8, _translate("MainWindow", "Август"))
        self.month_combo_box_b.setItemText(9, _translate("MainWindow", "Сентябрь"))
        self.month_combo_box_b.setItemText(10, _translate("MainWindow", "Октябрь"))
        self.month_combo_box_b.setItemText(11, _translate("MainWindow", "Ноябрь"))
        self.month_combo_box_b.setItemText(12, _translate("MainWindow", "Декабрь"))
        self.direction_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_b.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bachelor_course), _translate("MainWindow", "Бакалавриат"))
        self.foe_label_m.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_m.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_m.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_m.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_m.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_m.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.month_combo_box_m.setItemText(1, _translate("MainWindow", "Январь"))
        self.month_combo_box_m.setItemText(2, _translate("MainWindow", "Февраль"))
        self.month_combo_box_m.setItemText(3, _translate("MainWindow", "Март"))
        self.month_combo_box_m.setItemText(4, _translate("MainWindow", "Апрель"))
        self.month_combo_box_m.setItemText(5, _translate("MainWindow", "Май"))
        self.month_combo_box_m.setItemText(6, _translate("MainWindow", "Июнь"))
        self.month_combo_box_m.setItemText(7, _translate("MainWindow", "Июль"))
        self.month_combo_box_m.setItemText(8, _translate("MainWindow", "Август"))
        self.month_combo_box_m.setItemText(9, _translate("MainWindow", "Сентябрь"))
        self.month_combo_box_m.setItemText(10, _translate("MainWindow", "Октябрь"))
        self.month_combo_box_m.setItemText(11, _translate("MainWindow", "Ноябрь"))
        self.month_combo_box_m.setItemText(12, _translate("MainWindow", "Декабрь"))
        self.direction_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_m.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.master_course), _translate("MainWindow", "Магистратура"))
        self.foe_label_s.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_s.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_s.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_s.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_s.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_s.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.month_combo_box_s.setItemText(1, _translate("MainWindow", "Январь"))
        self.month_combo_box_s.setItemText(2, _translate("MainWindow", "Февраль"))
        self.month_combo_box_s.setItemText(3, _translate("MainWindow", "Март"))
        self.month_combo_box_s.setItemText(4, _translate("MainWindow", "Апрель"))
        self.month_combo_box_s.setItemText(5, _translate("MainWindow", "Май"))
        self.month_combo_box_s.setItemText(6, _translate("MainWindow", "Июнь"))
        self.month_combo_box_s.setItemText(7, _translate("MainWindow", "Июль"))
        self.month_combo_box_s.setItemText(8, _translate("MainWindow", "Август"))
        self.month_combo_box_s.setItemText(9, _translate("MainWindow", "Сентябрь"))
        self.month_combo_box_s.setItemText(10, _translate("MainWindow", "Октябрь"))
        self.month_combo_box_s.setItemText(11, _translate("MainWindow", "Ноябрь"))
        self.month_combo_box_s.setItemText(12, _translate("MainWindow", "Декабрь"))
        self.direction_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_s.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.specialist_degree), _translate("MainWindow",
                                                                                             "Специалитет"))
        self.foe_label_CSET.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_CSET.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_CSET.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_CSET.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_CSET.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_CSET.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.month_combo_box_CSET.setItemText(1, _translate("MainWindow", "Январь"))
        self.month_combo_box_CSET.setItemText(2, _translate("MainWindow", "Февраль"))
        self.month_combo_box_CSET.setItemText(3, _translate("MainWindow", "Март"))
        self.month_combo_box_CSET.setItemText(4, _translate("MainWindow", "Апрель"))
        self.month_combo_box_CSET.setItemText(5, _translate("MainWindow", "Май"))
        self.month_combo_box_CSET.setItemText(6, _translate("MainWindow", "Июнь"))
        self.month_combo_box_CSET.setItemText(7, _translate("MainWindow", "Июль"))
        self.month_combo_box_CSET.setItemText(8, _translate("MainWindow", "Август"))
        self.month_combo_box_CSET.setItemText(9, _translate("MainWindow", "Сентябрь"))
        self.month_combo_box_CSET.setItemText(10, _translate("MainWindow", "Октябрь"))
        self.month_combo_box_CSET.setItemText(11, _translate("MainWindow", "Ноябрь"))
        self.month_combo_box_CSET.setItemText(12, _translate("MainWindow", "Декабрь"))
        self.direction_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_CSET.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CSET), _translate("MainWindow", "ККМТ"))
        self.foe_label_TSTD.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_TSTD.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_TSTD.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_TSTD.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_TSTD.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_TSTD.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.month_combo_box_TSTD.setItemText(1, _translate("MainWindow", "Январь"))
        self.month_combo_box_TSTD.setItemText(2, _translate("MainWindow", "Февраль"))
        self.month_combo_box_TSTD.setItemText(3, _translate("MainWindow", "Март"))
        self.month_combo_box_TSTD.setItemText(4, _translate("MainWindow", "Апрель"))
        self.month_combo_box_TSTD.setItemText(5, _translate("MainWindow", "Май"))
        self.month_combo_box_TSTD.setItemText(6, _translate("MainWindow", "Июнь"))
        self.month_combo_box_TSTD.setItemText(7, _translate("MainWindow", "Июль"))
        self.month_combo_box_TSTD.setItemText(8, _translate("MainWindow", "Август"))
        self.month_combo_box_TSTD.setItemText(9, _translate("MainWindow", "Сентябрь"))
        self.month_combo_box_TSTD.setItemText(10, _translate("MainWindow", "Октябрь"))
        self.month_combo_box_TSTD.setItemText(11, _translate("MainWindow", "Ноябрь"))
        self.month_combo_box_TSTD.setItemText(12, _translate("MainWindow", "Декабрь"))
        self.direction_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_TSTD.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TSTD), _translate("MainWindow", "ТТД"))
        self.last_month_label.setText(_translate("MainWindow", "По сравнению с предыдущим месяцем:"))
        self.last_year_label.setText(_translate("MainWindow", "По сравнению с этим месяцем прошлого года:"))
        self.back_button.setText(_translate("MainWindow", "Назад"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
