from PyQt5 import QtCore, QtGui, QtWidgets


class UiWindow:
    def __init__(self, window):
        """Конструктор класса UiWindow"""
        super(UiWindow, self).__init__()
        window.setObjectName("MainWindow")
        window.resize(1019, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Изображения/free-icon-binder-4624080.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        window.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.tabWidget.setObjectName("tabWidget")
        self.bachelor_course = QtWidgets.QWidget()
        self.bachelor_course.setStyleSheet("")
        self.bachelor_course.setObjectName("bachelor_course")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.bachelor_course)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_widget_b = QtWidgets.QTableWidget(self.bachelor_course)
        self.table_widget_b.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_widget_b.setFont(font)
        self.table_widget_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_b.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_widget_b.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_widget_b.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_widget_b.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.table_widget_b.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_widget_b.setShowGrid(True)
        self.table_widget_b.setGridStyle(QtCore.Qt.SolidLine)
        self.table_widget_b.setCornerButtonEnabled(False)
        self.table_widget_b.setRowCount(0)
        self.table_widget_b.setColumnCount(30)
        self.table_widget_b.setObjectName("table_widget_b")
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_b.setHorizontalHeaderItem(29, item)
        self.table_widget_b.horizontalHeader().setVisible(True)
        self.table_widget_b.horizontalHeader().setCascadingSectionResizes(False)
        self.table_widget_b.horizontalHeader().setDefaultSectionSize(100)
        self.table_widget_b.horizontalHeader().setHighlightSections(True)
        self.table_widget_b.horizontalHeader().setStretchLastSection(False)
        self.table_widget_b.verticalHeader().setVisible(True)
        self.table_widget_b.verticalHeader().setCascadingSectionResizes(False)
        self.table_widget_b.verticalHeader().setDefaultSectionSize(30)
        self.table_widget_b.verticalHeader().setMinimumSectionSize(30)
        self.table_widget_b.verticalHeader().setSortIndicatorShown(True)
        self.table_widget_b.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.table_widget_b, 1, 0, 1, 1)
        self.grid_layout_b = QtWidgets.QGridLayout()
        self.grid_layout_b.setObjectName("grid_layout_b")
        self.foe_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.foe_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_b.setFont(font)
        self.foe_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_b.setObjectName("foe_label_b")
        self.grid_layout_b.addWidget(self.foe_label_b, 0, 0, 1, 1)
        self.foe_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_b.setFont(font)
        self.foe_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_b.setObjectName("foe_combo_box_b")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.foe_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.foe_combo_box_b, 1, 0, 1, 1)
        self.direction_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.direction_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_b.setFont(font)
        self.direction_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_b.setObjectName("direction_label_b")
        self.grid_layout_b.addWidget(self.direction_label_b, 0, 1, 1, 1)
        self.year_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_b.setFont(font)
        self.year_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_b.setObjectName("year_combo_box_b")
        self.year_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.year_combo_box_b, 1, 2, 1, 1)
        self.year_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.year_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_b.setFont(font)
        self.year_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_b.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_b.setObjectName("year_label_b")
        self.grid_layout_b.addWidget(self.year_label_b, 0, 2, 1, 1)
        self.month_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_b.setFont(font)
        self.month_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_b.setObjectName("month_combo_box_b")
        self.month_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.month_combo_box_b, 1, 3, 1, 1)
        self.direction_combo_box_b = QtWidgets.QComboBox(self.bachelor_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_b.setFont(font)
        self.direction_combo_box_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_b.setObjectName("direction_combo_box_b")
        self.direction_combo_box_b.addItem("")
        self.grid_layout_b.addWidget(self.direction_combo_box_b, 1, 1, 1, 1)
        self.month_label_b = QtWidgets.QLabel(self.bachelor_course)
        self.month_label_b.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_b.setFont(font)
        self.month_label_b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_b.setObjectName("month_label_b")
        self.grid_layout_b.addWidget(self.month_label_b, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.grid_layout_b, 0, 0, 1, 1)
        self.tabWidget.addTab(self.bachelor_course, "")
        self.master_course = QtWidgets.QWidget()
        self.master_course.setObjectName("master_course")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.master_course)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grid_layout_m = QtWidgets.QGridLayout()
        self.grid_layout_m.setObjectName("grid_layout_m")
        self.foe_label_m = QtWidgets.QLabel(self.master_course)
        self.foe_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_m.setFont(font)
        self.foe_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_m.setObjectName("foe_label_m")
        self.grid_layout_m.addWidget(self.foe_label_m, 0, 0, 1, 1)
        self.foe_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_m.setFont(font)
        self.foe_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_m.setObjectName("foe_combo_box_m")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.foe_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.foe_combo_box_m, 1, 0, 1, 1)
        self.direction_label_m = QtWidgets.QLabel(self.master_course)
        self.direction_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_m.setFont(font)
        self.direction_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_m.setObjectName("direction_label_m")
        self.grid_layout_m.addWidget(self.direction_label_m, 0, 1, 1, 1)
        self.year_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_m.setFont(font)
        self.year_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_m.setObjectName("year_combo_box_m")
        self.year_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.year_combo_box_m, 1, 2, 1, 1)
        self.year_label_m = QtWidgets.QLabel(self.master_course)
        self.year_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_m.setFont(font)
        self.year_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_m.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_m.setObjectName("year_label_m")
        self.grid_layout_m.addWidget(self.year_label_m, 0, 2, 1, 1)
        self.month_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_m.setFont(font)
        self.month_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_m.setObjectName("month_combo_box_m")
        self.month_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.month_combo_box_m, 1, 3, 1, 1)
        self.direction_combo_box_m = QtWidgets.QComboBox(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_m.setFont(font)
        self.direction_combo_box_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_m.setObjectName("direction_combo_box_m")
        self.direction_combo_box_m.addItem("")
        self.grid_layout_m.addWidget(self.direction_combo_box_m, 1, 1, 1, 1)
        self.month_label_m = QtWidgets.QLabel(self.master_course)
        self.month_label_m.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_m.setFont(font)
        self.month_label_m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_m.setObjectName("month_label_m")
        self.grid_layout_m.addWidget(self.month_label_m, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.grid_layout_m, 0, 0, 1, 1)
        self.table_widget_m = QtWidgets.QTableWidget(self.master_course)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_widget_m.setFont(font)
        self.table_widget_m.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_m.setRowCount(0)
        self.table_widget_m.setColumnCount(30)
        self.table_widget_m.setObjectName("table_widget_m")
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_m.setHorizontalHeaderItem(29, item)
        self.gridLayout_6.addWidget(self.table_widget_m, 1, 0, 1, 1)
        self.tabWidget.addTab(self.master_course, "")
        self.specialist_degree = QtWidgets.QWidget()
        self.specialist_degree.setObjectName("specialist_degree")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.specialist_degree)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.grid_layout_s = QtWidgets.QGridLayout()
        self.grid_layout_s.setObjectName("grid_layout_s")
        self.foe_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.foe_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_s.setFont(font)
        self.foe_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_s.setObjectName("for_label_s")
        self.grid_layout_s.addWidget(self.foe_label_s, 0, 0, 1, 1)
        self.foe_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_s.setFont(font)
        self.foe_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_s.setObjectName("foe_combo_box_s")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.foe_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.foe_combo_box_s, 1, 0, 1, 1)
        self.direction_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.direction_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_s.setFont(font)
        self.direction_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_s.setObjectName("direction_label_s")
        self.grid_layout_s.addWidget(self.direction_label_s, 0, 1, 1, 1)
        self.year_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_s.setFont(font)
        self.year_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_s.setObjectName("year_combo_box_s")
        self.year_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.year_combo_box_s, 1, 2, 1, 1)
        self.year_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.year_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_s.setFont(font)
        self.year_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_s.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_s.setObjectName("year_label_s")
        self.grid_layout_s.addWidget(self.year_label_s, 0, 2, 1, 1)
        self.month_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_s.setFont(font)
        self.month_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_s.setObjectName("month_combo_box_s")
        self.month_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.month_combo_box_s, 1, 3, 1, 1)
        self.direction_combo_box_s = QtWidgets.QComboBox(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_s.setFont(font)
        self.direction_combo_box_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_s.setObjectName("direction_combo_box_s")
        self.direction_combo_box_s.addItem("")
        self.grid_layout_s.addWidget(self.direction_combo_box_s, 1, 1, 1, 1)
        self.month_label_s = QtWidgets.QLabel(self.specialist_degree)
        self.month_label_s.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_s.setFont(font)
        self.month_label_s.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_s.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_s.setObjectName("month_label_s")
        self.grid_layout_s.addWidget(self.month_label_s, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.grid_layout_s, 0, 0, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.specialist_degree)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(30)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(29, item)
        self.gridLayout_8.addWidget(self.tableWidget_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.specialist_degree, "")
        self.cset = QtWidgets.QWidget()
        self.cset.setObjectName("cset")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.cset)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.grid_layout_CSET = QtWidgets.QGridLayout()
        self.grid_layout_CSET.setObjectName("grid_layout_CSET")
        self.foe_label_CSET = QtWidgets.QLabel(self.cset)
        self.foe_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_CSET.setFont(font)
        self.foe_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_CSET.setObjectName("foe_label_CSET")
        self.grid_layout_CSET.addWidget(self.foe_label_CSET, 0, 0, 1, 1)
        self.foe_combo_box_CSET = QtWidgets.QComboBox(self.cset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_CSET.setFont(font)
        self.foe_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_CSET.setObjectName("foe_combo_box_CSET")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.foe_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.foe_combo_box_CSET, 1, 0, 1, 1)
        self.direction_label_CSET = QtWidgets.QLabel(self.cset)
        self.direction_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_CSET.setFont(font)
        self.direction_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_CSET.setObjectName("direction_label_CSET")
        self.grid_layout_CSET.addWidget(self.direction_label_CSET, 0, 1, 1, 1)
        self.year_combo_box_CSET = QtWidgets.QComboBox(self.cset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_CSET.setFont(font)
        self.year_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_CSET.setObjectName("year_combo_box_CSET")
        self.year_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.year_combo_box_CSET, 1, 2, 1, 1)
        self.year_label_CSET = QtWidgets.QLabel(self.cset)
        self.year_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_CSET.setFont(font)
        self.year_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_CSET.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_CSET.setObjectName("year_label_CSET")
        self.grid_layout_CSET.addWidget(self.year_label_CSET, 0, 2, 1, 1)
        self.month_combo_box_CSET = QtWidgets.QComboBox(self.cset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_CSET.setFont(font)
        self.month_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_CSET.setObjectName("month_combo_box_CSET")
        self.month_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.month_combo_box_CSET, 1, 3, 1, 1)
        self.direction_combo_box_CSET = QtWidgets.QComboBox(self.cset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_CSET.setFont(font)
        self.direction_combo_box_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_CSET.setObjectName("direction_combo_box_CSET")
        self.direction_combo_box_CSET.addItem("")
        self.grid_layout_CSET.addWidget(self.direction_combo_box_CSET, 1, 1, 1, 1)
        self.month_label_CSET = QtWidgets.QLabel(self.cset)
        self.month_label_CSET.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_CSET.setFont(font)
        self.month_label_CSET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_CSET.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_CSET.setObjectName("month_label_CSET")
        self.grid_layout_CSET.addWidget(self.month_label_CSET, 0, 3, 1, 1)
        self.gridLayout_10.addLayout(self.grid_layout_CSET, 0, 0, 1, 1)
        self.table_widget_CSET = QtWidgets.QTableWidget(self.cset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_widget_CSET.setFont(font)
        self.table_widget_CSET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_CSET.setObjectName("table_widget_CSET")
        self.table_widget_CSET.setColumnCount(30)
        self.table_widget_CSET.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_CSET.setHorizontalHeaderItem(29, item)
        self.gridLayout_10.addWidget(self.table_widget_CSET, 1, 0, 1, 1)
        self.tabWidget.addTab(self.cset, "")
        self.tstd = QtWidgets.QWidget()
        self.tstd.setObjectName("tstd")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tstd)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.grid_layout_TSTD = QtWidgets.QGridLayout()
        self.grid_layout_TSTD.setObjectName("grid_layout_TSTD")
        self.foe_label_TSTD = QtWidgets.QLabel(self.tstd)
        self.foe_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_label_TSTD.setFont(font)
        self.foe_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.foe_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.foe_label_TSTD.setObjectName("foe_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.foe_label_TSTD, 0, 0, 1, 1)
        self.foe_combo_box_TSTD = QtWidgets.QComboBox(self.tstd)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.foe_combo_box_TSTD.setFont(font)
        self.foe_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foe_combo_box_TSTD.setObjectName("foe_combo_box_TSTD")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.foe_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.foe_combo_box_TSTD, 1, 0, 1, 1)
        self.direction_label_TSTD = QtWidgets.QLabel(self.tstd)
        self.direction_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_label_TSTD.setFont(font)
        self.direction_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.direction_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_label_TSTD.setObjectName("direction_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.direction_label_TSTD, 0, 1, 1, 1)
        self.year_combo_box_TSTD = QtWidgets.QComboBox(self.tstd)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_combo_box_TSTD.setFont(font)
        self.year_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_combo_box_TSTD.setObjectName("year_combo_box_TSTD")
        self.year_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.year_combo_box_TSTD, 1, 2, 1, 1)
        self.year_label_TSTD = QtWidgets.QLabel(self.tstd)
        self.year_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.year_label_TSTD.setFont(font)
        self.year_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.year_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.year_label_TSTD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label_TSTD.setObjectName("year_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.year_label_TSTD, 0, 2, 1, 1)
        self.month_combo_box_TSTD = QtWidgets.QComboBox(self.tstd)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_combo_box_TSTD.setFont(font)
        self.month_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_combo_box_TSTD.setObjectName("month_combo_box_TSTD")
        self.month_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.month_combo_box_TSTD, 1, 3, 1, 1)
        self.direction_combo_box_TSTD = QtWidgets.QComboBox(self.tstd)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direction_combo_box_TSTD.setFont(font)
        self.direction_combo_box_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.direction_combo_box_TSTD.setObjectName("direction_combo_box_TSTD")
        self.direction_combo_box_TSTD.addItem("")
        self.grid_layout_TSTD.addWidget(self.direction_combo_box_TSTD, 1, 1, 1, 1)
        self.month_label_TSTD = QtWidgets.QLabel(self.tstd)
        self.month_label_TSTD.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.month_label_TSTD.setFont(font)
        self.month_label_TSTD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.month_label_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.month_label_TSTD.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label_TSTD.setObjectName("month_label_TSTD")
        self.grid_layout_TSTD.addWidget(self.month_label_TSTD, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.grid_layout_TSTD, 0, 0, 1, 1)
        self.table_widget_TSTD = QtWidgets.QTableWidget(self.tstd)
        self.table_widget_TSTD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_widget_TSTD.setObjectName("table_widget_TSTD")
        self.table_widget_TSTD.setColumnCount(30)
        self.table_widget_TSTD.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_TSTD.setHorizontalHeaderItem(29, item)
        self.gridLayout_12.addWidget(self.table_widget_TSTD, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tstd, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(window)
        self.toolBar.setObjectName("toolBar")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslate_ui(window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        """Установка всех названий"""
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "StudInStudOut"))
        self.table_widget_b.setSortingEnabled(True)
        item = self.table_widget_b.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код направления подготовки"))
        item = self.table_widget_b.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Названия направления подготовки"))
        item = self.table_widget_b.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень обучения"))
        item = self.table_widget_b.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Форма обучения"))
        item = self.table_widget_b.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата записи"))
        item = self.table_widget_b.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Курс"))
        item = self.table_widget_b.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Всего зачислено"))
        item = self.table_widget_b.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего зачислено)"))
        item = self.table_widget_b.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего зачислено)"))
        item = self.table_widget_b.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего зачислено)"))
        item = self.table_widget_b.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Всего отчислено"))
        item = self.table_widget_b.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего отчислено)"))
        item = self.table_widget_b.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего отчислено)"))
        item = self.table_widget_b.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего отчислено)"))
        item = self.table_widget_b.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Зачислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_b.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Зачислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_b.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено платное)"))
        item = self.table_widget_b.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено платное)"))
        item = self.table_widget_b.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено платное)"))
        item = self.table_widget_b.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Отчислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_b.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено бюджет)"))
        item = self.table_widget_b.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Отчислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_b.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено платное)"))
        item = self.table_widget_b.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено платное)"))
        item = self.table_widget_b.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено платное)"))
        self.foe_label_b.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_b.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_b.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_b.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_b.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_b.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.direction_combo_box_b.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_b.setText(_translate("MainWindow", "Месяц"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bachelor_course), _translate("MainWindow", "Бакалавриат"))
        self.foe_label_m.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_m.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_m.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_m.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_m.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_m.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.direction_combo_box_m.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_m.setText(_translate("MainWindow", "Месяц"))
        item = self.table_widget_m.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код направления подготовки"))
        item = self.table_widget_m.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Названия направления подготовки"))
        item = self.table_widget_m.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень обучения"))
        item = self.table_widget_m.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Форма обучения"))
        item = self.table_widget_m.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата записи"))
        item = self.table_widget_m.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Курс"))
        item = self.table_widget_m.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Всего зачислено"))
        item = self.table_widget_m.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего зачислено)"))
        item = self.table_widget_m.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего зачислено)"))
        item = self.table_widget_m.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего зачислено)"))
        item = self.table_widget_m.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Всего отчислено"))
        item = self.table_widget_m.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего отчислено)"))
        item = self.table_widget_m.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего отчислено)"))
        item = self.table_widget_m.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего отчислено)"))
        item = self.table_widget_m.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Зачислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_m.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Зачислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_m.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено платное)"))
        item = self.table_widget_m.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено платное)"))
        item = self.table_widget_m.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено платное)"))
        item = self.table_widget_m.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Отчислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_m.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено бюджет)"))
        item = self.table_widget_m.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Отчислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_m.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено платное)"))
        item = self.table_widget_m.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено платное)"))
        item = self.table_widget_m.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено платное)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.master_course), _translate("MainWindow", "Магистратура"))
        self.foe_label_s.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_s.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_s.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_s.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_s.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_s.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.direction_combo_box_s.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_s.setText(_translate("MainWindow", "Месяц"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код направления подготовки"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Названия направления подготовки"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень обучения"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Форма обучения"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата записи"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Курс"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Всего зачислено"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего зачислено)"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего зачислено)"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего зачислено"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Всего отчислено"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего отчислено)"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего отчислено)"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего отчислено)"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Зачислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Зачислено по договорам об оказании платных образовательных услуг"))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено платное)"))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено платное)"))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено платное)"))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Отчислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено бюджет)"))
        item = self.tableWidget_3.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Отчислено по договорам об оказании платных образовательных услуг"))
        item = self.tableWidget_3.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено платное)"))
        item = self.tableWidget_3.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено платное)"))
        item = self.tableWidget_3.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено платное)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.specialist_degree), _translate("MainWindow",
                                                                                             "Специалитет"))
        self.foe_label_CSET.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_CSET.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_CSET.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_CSET.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_CSET.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_CSET.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.direction_combo_box_CSET.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_CSET.setText(_translate("MainWindow", "Месяц"))
        item = self.table_widget_CSET.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код направления подготовки"))
        item = self.table_widget_CSET.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Названия направления подготовки"))
        item = self.table_widget_CSET.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень обучения"))
        item = self.table_widget_CSET.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Форма обучения"))
        item = self.table_widget_CSET.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата записи"))
        item = self.table_widget_CSET.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Курс"))
        item = self.table_widget_CSET.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Всего зачислено"))
        item = self.table_widget_CSET.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего зачислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего зачислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего зачислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Всего отчислено"))
        item = self.table_widget_CSET.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего отчислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего отчислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего отчислено)"))
        item = self.table_widget_CSET.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Зачислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_CSET.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Зачислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_CSET.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено платное)"))
        item = self.table_widget_CSET.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено платное)"))
        item = self.table_widget_CSET.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено платное)"))
        item = self.table_widget_CSET.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Отчислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_CSET.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено бюджет)"))
        item = self.table_widget_CSET.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Отчислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_CSET.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено платное)"))
        item = self.table_widget_CSET.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено платное)"))
        item = self.table_widget_CSET.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено платное)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cset), _translate("MainWindow", "ККМТ"))
        self.foe_label_TSTD.setText(_translate("MainWindow", "Форма обучения"))
        self.foe_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.foe_combo_box_TSTD.setItemText(1, _translate("MainWindow", "Очная"))
        self.foe_combo_box_TSTD.setItemText(2, _translate("MainWindow", "Очно-заочная"))
        self.foe_combo_box_TSTD.setItemText(3, _translate("MainWindow", "Заочная"))
        self.direction_label_TSTD.setText(_translate("MainWindow", "Направление"))
        self.year_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.year_label_TSTD.setText(_translate("MainWindow", "Год"))
        self.month_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.direction_combo_box_TSTD.setItemText(0, _translate("MainWindow", "Все"))
        self.month_label_TSTD.setText(_translate("MainWindow", "Месяц"))
        item = self.table_widget_TSTD.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код направления подготовки"))
        item = self.table_widget_TSTD.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Названия направления подготовки"))
        item = self.table_widget_TSTD.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень обучения"))
        item = self.table_widget_TSTD.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Форма обучения"))
        item = self.table_widget_TSTD.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата записи"))
        item = self.table_widget_TSTD.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Курс"))
        item = self.table_widget_TSTD.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Всего зачислено"))
        item = self.table_widget_TSTD.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего зачислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего зачислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего зачислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Всего отчислено"))
        item = self.table_widget_TSTD.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (всего отчислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (всего отчислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (всего отчислено)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Зачислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_TSTD.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Зачислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_TSTD.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (зачислено платное)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (зачислено платное)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (зачислено платное)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Отчислено за счет бюджетных ассигнований бюджета субъекта РФ"))
        item = self.table_widget_TSTD.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено бюджет)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Отчислено по договорам об оказании платных образовательных услуг"))
        item = self.table_widget_TSTD.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Из них лица с ОВЗ, инвалиды, дети-инвалиды (отчислено платное)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "Из них на места в рамках квоты целевого приема (отчислено платное)"))
        item = self.table_widget_TSTD.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Из них иностранные граждане (отчислено платное)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tstd), _translate("MainWindow", "ТТД"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
